name: test
on: [push, pull_request]

jobs:
  lint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Install deps
        run: make deps-test
      - name: Run test
        run: make test